// 单词释义表 —— 练习模式里鼠标悬停在单词上时弹出的中文意思。
//
// 为什么是手写的: 这项目离线跑(file://), 没有网络也没有词典库。要悬停即译,
// 只能把题库里出现过的词一个个列出来。生成器推不出来这个, 所以单独一个文件。
//
// 格式: WORD_DICT[小写词形] = '中文'
//   - 键一律小写; 查询时会把词尾的撇号去掉(johnsons' → johnsons)
//   - 一词多义时给题库里最常用的那个意思, 必要时用"；"并列
//   - 查不到的词不报错, 只是悬停不弹东西
//
// tests/qb_dict.html 会检查题库里每个单词都有条目, 缺了会点名。
// 以后往题库加新题, 跑一遍测试就知道漏了哪些词。

window.WORD_DICT = {
  /* ---- a ---- */
  'a': '一个',
  'ability': '能力',
  'about': '关于；大约',
  'accept': '接受',
  'accommodation': '住宿；住处',
  'according': '根据 (according to)',
  'accumulation': '积累；堆积',
  'activity': '活动',
  'address': '地址；演说',
  'ads': '广告',
  'afford': '负担得起',
  'after': '在…之后',
  'again': '再；又',
  'against': '反对；靠着',
  'aged': '年老的',
  'airport': '机场',
  'alan': '艾伦（人名）',
  'all': '全部',
  'almost': '几乎',
  'alone': '独自',
  'also': '也',
  'although': '虽然',
  'always': '总是',
  'am': '是（be 动词）',
  'amount': '数量；金额',
  'an': '一个',
  'and': '和',
  'another': '另一个',
  'any': '任何',
  'anything': '任何事物',
  'apart': '分开；相隔',
  'apple': '苹果',
  'approval': '批准；认可',
  'approvals': '批准；认可',
  'are': '是（be 动词）',
  'area': '地区；面积',
  'around': '周围；大约',
  'arrest': '逮捕',
  'as': '作为；如同',
  'asleep': '睡着的',
  'assume': '假定；认为',
  'assumed': '假定；认为',
  'at': '在',
  'attribute': '归因于；属性',
  'away': '离开；远离',

  /* ---- b ---- */
  'bare': '赤裸的；空的',
  'base': '基础；基地',
  'be': '是',
  'because': '因为',
  'become': '变成',
  'bed': '床',
  'before': '在…之前',
  'belongings': '随身物品',
  'below': '在…下面',
  'better': '更好的',
  'blank': '空白',
  'busy': '忙的',
  'but': '但是',
  'buy': '买',

  /* ---- c ---- */
  'call': '叫；打电话',
  'can': '能；可以',
  "can't": '不能',
  'capability': '能力',
  'capacity': '容量；能力',
  'card': '卡片',
  'care': '关心；照料',
  'careful': '小心的',
  'carefully': '小心地',
  'carry': '携带；搬运',
  'case': '情况；箱子',
  'cat': '猫',
  'catch': '抓住；赶上',
  'change': '改变',
  'chase': '追赶',
  'children': '孩子们',
  'china': '中国',
  'chinese': '中国的；中文',
  'choice': '选择',
  'choose': '选择',
  'cities': '城市（复数）',
  'city': '城市',
  'class': '班级；阶级',
  'clients': '客户',
  'college': '大学',
  'come': '来',
  'comment': '评论',
  'common': '常见的；共同的',
  'company': '公司；陪伴',
  'compare': '比较',
  'composition': '作文；构成',
  'compress': '压缩',
  'compresses': '压缩',
  'conclusion': '结论',
  'conclusions': '结论',
  'concrete': '混凝土；具体的',
  'condense': '冷凝；浓缩',
  'condenses': '冷凝；浓缩',
  'conditions': '条件；状况',
  'considered': '被认为',
  'contact': '联系',
  'contract': '合同；收缩',
  'contracts': '合同',
  'contribute': '贡献；促成',
  'convenient': '方便的',
  'cooler': '更凉的；冷却器',
  'could': '能够（can 的过去式）',
  'credit': '信用；学分',
  'crowds': '人群',
  'customers': '顾客',

  /* ---- d ---- */
  'daily': '每日的',
  'data': '数据',
  'day': '天',
  'days': '天（复数）',
  'decision': '决定',
  'demonstrators': '示威者；演示者',
  'designed': '设计的',
  'developed': '发达的；开发的',
  "didn't": '没有',
  'differ': '不同',
  'difficult': '困难的',
  'difficulty': '困难',
  'discussion': '讨论',
  'do': '做',
  'doing': '做（do 的 -ing 形式）',
  'done': '做（do 的过去分词）',
  'draw': '画；拉；得出 (draw a conclusion)',
  'drawn': '拉；画（过去分词）',

  /* ---- e ---- */
  'each': '每个',
  'eating': '吃',
  'eight': '八',
  'either': '也（不）；两者之一',
  'else': '别的',
  'email': '电子邮件',
  'employees': '雇员',
  'english': '英语',
  'estimate': '估计',
  'estimated': '估计',
  'eton': '伊顿（英国名校）',
  'evaluate': '评估',
  'evaluated': '评估',
  'even': '甚至',
  'every': '每个',
  'everything': '一切',
  'evidence': '证据',
  'exam': '考试',
  'examination': '考试；检查',
  'expand': '膨胀；扩展',
  'expands': '膨胀；扩展',
  'expose': '暴露',
  'extra': '额外的',
  'extremely': '极其',

  /* ---- f ---- */
  'failure': '失败',
  'fairly': '相当；公平地',
  'farming': '农业',
  'fall': '落下 (fall asleep 入睡)',
  'fast': '快的',
  'feel': '感觉',
  'fell': '落下（fall 的过去式）',
  'final': '最终的',
  'find': '找到；发现',
  'finding': '发现；调查结果',
  'fine': '好的；罚款',
  'first': '第一',
  'for': '为了',
  'forward': '向前',
  'found': '找到（过去式）；建立',
  'free': '自由的；免费的',
  'from': '从',
  'front': '前面',
  'further': '进一步',

  /* ---- g ---- */
  'gas': '气体；汽油',
  'generators': '发电机',
  'get': '得到',
  'getting': '得到',
  'girls': '女孩们',
  'given': '给定的',
  'go': '去',
  'gone': '去了',
  'good': '好的',
  'got': '得到（过去式）',
  'government': '政府',
  'great': '伟大的；很好的',
  'greatly': '大大地',
  'grows': '生长',

  /* ---- h ---- */
  'habits': '习惯',
  'had': '有（过去式）',
  'happily': '快乐地',
  'has': '有',
  'have': '有',
  'he': '他',
  'health': '健康',
  'healthful': '有益健康的',
  'healthily': '健康地',
  'healthy': '健康的',
  'help': '帮助',
  'her': '她的；她',
  'high': '高的',
  'hills': '小山',
  'him': '他',
  'his': '他的',
  'hollow': '空的；中空的',
  'home': '家',
  'hot': '热的',
  'hours': '小时',
  'house': '房子',

  /* ---- i ---- */
  'i': '我',
  "i'm": '我是',
  'idea': '主意',
  'if': '如果',
  'impossible': '不可能的',
  'improve': '改善',
  'in': '在…里',
  'inadequate': '不充足的',
  'installation': '安装',
  'insurance': '保险',
  'internet': '互联网',
  'invite': '邀请',
  'is': '是（be 动词）',
  'it': '它',
  "it's": '它是',

  /* ---- j ---- */
  'job': '工作',
  'jobs': '工作（复数）',
  'john': '约翰（人名）',
  'johnsons': '约翰逊一家',
  'judge': '判断；法官',
  'judged': '判断',
  'justifiable': '有正当理由的',

  /* ---- k ---- */
  'keen': '热衷的；敏锐的',
  'kilowatt': '千瓦',
  'know': '知道',
  'known': '已知的',

  /* ---- l ---- */
  'lacks': '缺乏',
  'large': '大的',
  'lasted': '持续',
  'lead': '领导；铅',
  'least': '最少',
  'left': '左边；离开（过去式）',
  'lest': '以免',
  'let': '让',
  "let's": '让我们',
  'libraries': '图书馆',
  'life': '生活',
  'like': '喜欢；像',
  'likes': '喜欢',
  'liquid': '液体',
  'live': '居住；活的',
  'lonely': '孤独的',
  'long': '长的',
  'loud': '大声的',
  'love': '爱',

  /* ---- m ---- */
  'made': '做（过去式）',
  'make': '做',
  'man': '男人',
  'manager': '经理',
  'many': '许多',
  'matter': '事情；要紧',
  'may': '可以；可能',
  'mayor': '市长',
  'me': '我',
  'media': '媒体',
  'message': '消息',
  'metal': '金属',
  'method': '方法',
  'mice': '老鼠（复数）',
  'might': '可能',
  'million': '百万',
  'mind': '头脑；介意 (make up one\'s mind 下定决心)',
  'minds': '头脑；介意',
  'missing': '失踪的；缺少的',
  'money': '钱',
  'more': '更多',
  'most': '最多',
  'much': '许多',
  'must': '必须',
  'my': '我的',

  /* ---- n ---- */
  'need': '需要',
  'neither': '两者都不',
  'new': '新的',
  'no': '不；没有',
  'nobody': '没有人',
  'none': '没有一个',
  'not': '不',
  'nothing': '没有什么',
  'now': '现在',
  'nowadays': '如今',
  'number': '数字；号码',

  /* ---- o ---- */
  'of': '…的',
  'off': '关掉；离开',
  'offer': '提供',
  'offerings': '提供物；课程',
  'often': '经常',
  'old': '老的',
  'on': '在…上',
  'once': '一次；曾经',
  'one': '一',
  "one's": '某人的',
  'only': '只有',
  'opened': '打开',
  'opinion': '意见',
  'optimistic': '乐观的',
  'or': '或者',
  'oral': '口头的',
  'order': '命令；顺序；订购',
  'other': '其他的',
  'our': '我们的',
  'out': '外面',
  'outline': '提纲',
  'over': '在…之上；超过',
  'own': '自己的',

  /* ---- p ---- */
  'part': '部分',
  'passed': '通过；经过',
  'passport': '护照',
  'past': '过去',
  'peacekeepers': '维和人员',
  'people': '人们',
  'perfect': '完美的',
  'performance': '表现；演出',
  'person': '人',
  'persuaded': '说服',
  'phones': '电话',
  'pick': '挑选；采摘',
  'pictures': '图片',
  'place': '地方',
  'plant': '工厂；植物',
  'playing': '玩；播放',
  'police': '警察',
  'poorly': '很差地',
  'possible': '可能的',
  'practice': '练习',
  'preliminary': '初步的',
  'preparations': '准备工作',
  'prescribe': '开处方；规定',
  'prescribing': '开处方；规定',
  'present': '现在的；出席的；礼物',
  'prices': '价格',
  'problem': '问题',
  'problems': '问题（复数）',
  'produce': '生产',
  'products': '产品',
  'proof': '证据',
  'proposals': '提议',
  'prosecute': '起诉',
  'prosecuting': '起诉',
  'protect': '保护',
  'protecting': '保护',
  'protest': '抗议',
  'protesting': '抗议',
  'proud': '自豪的',
  'pupil': '小学生',
  'pursue': '追求',

  /* ---- q ---- */
  'quantity': '数量',
  'quite': '相当',

  /* ---- r ---- */
  'race': '比赛；种族',
  'ran': '跑（run 的过去式）',
  'rather': '相当；宁愿',
  'read': '读',
  'realize': '意识到',
  'realized': '意识到',
  'really': '真的',
  'reason': '原因；理由',
  'reasons': '原因',
  'receive': '收到',
  'regain': '重新获得',
  'region': '地区',
  'reinforce': '加强',
  'relax': '放松',
  'release': '释放；发布',
  'reliable': '可靠的',
  'rents': '租金',
  'represent': '代表',
  'resolve': '解决；决心',
  'respect': '尊重',
  'respectable': '体面的；可敬的',
  'respectful': '恭敬的',
  'respecting': '关于；尊重',
  'respective': '各自的',
  'responsibility': '责任',
  'result': '结果',
  'retreat': '撤退',
  'retreats': '撤退',
  'reveal': '揭示',
  'right': '对的；右边',
  'rises': '上升',
  'risk': '风险',
  'round': '圆的；一轮',
  'run': '跑；经营',

  /* ---- s ---- */
  'said': '说（say 的过去式）',
  'sales': '销售',
  'samples': '样品',
  'satisfactory': '令人满意的',
  'satisfied': '满意的',
  'say': '说',
  'sb': '某人（somebody 的缩写）',
  'scarcely': '几乎不',
  'school': '学校',
  'scientific': '科学的',
  'second': '第二；秒',
  'see': '看见',
  'seeing': '看见',
  'self-confidence': '自信',
  'sense': '感觉；意义',
  'sent': '寄送（send 的过去式）',
  'shopping': '购物',
  'should': '应该',
  'since': '自从；因为',
  'situation': '情况',
  'sleeping': '睡觉',
  'sleepy': '困的',
  'slept': '睡（sleep 的过去式）',
  'so': '所以；如此',
  'sold': '卖（sell 的过去式）',
  'solid': '固体的；结实的',
  'some': '一些',
  'somebody': '某人',
  'something': '某事',
  'soon': '不久',
  'sooner': '更早',
  'sorry': '抱歉的',
  'source': '来源',
  'sources': '来源',
  'spend': '花费',
  'spirit': '精神',
  'spite': '恶意（in spite of 尽管）',
  'spokesman': '发言人',
  'stand': '站立；忍受',
  'step': '步骤',
  'sth': '某事／某物（something 的缩写）',
  'still': '仍然',
  'stop': '停止',
  'student': '学生',
  'students': '学生们',
  'such': '这样的 (such + 名词 + that)',
  'success': '成功',
  'sufficient': '足够的',

  /* ---- t ---- */
  'taken': '拿（take 的过去分词）',
  'talk': '谈话',
  'talking': '谈话',
  'task': '任务',
  'teacher': '老师',
  'temperature': '温度',
  'than': '比',
  'that': '那个',
  'the': '这个／那个（定冠词）',
  'their': '他们的',
  'them': '他们',
  'there': '那里',
  'therefore': '因此',
  'these': '这些',
  'they': '他们',
  'thing': '事情',
  'things': '东西',
  'this': '这个',
  'those': '那些',
  'though': '虽然',
  'three': '三',
  'through': '穿过',
  'time': '时间',
  'tired': '累的',
  'to': '到；向',
  "today's": '今天的',
  'tonight': '今晚',
  'too': '也；太',
  'topic': '话题',
  'tops': '顶部',
  'travel': '旅行',
  'trees': '树',
  'troops': '军队',
  'turbine': '涡轮机',
  'tv': '电视',

  /* ---- u ---- */
  'un': '联合国（the UN）',
  'under': '在…下',
  'unique': '独特的',
  'unless': '除非',
  'unpleasant': '令人不快的',
  'until': '直到',
  'up': '向上',
  'us': '我们',
  'use': '使用',

  /* ---- v ---- */
  'vacant': '空的；空缺的',
  'very': '非常',
  'villages': '村庄',
  'visit': '拜访',

  /* ---- w ---- */
  'want': '想要',
  'war': '战争',
  'was': '是（be 的过去式）',
  'way': '方式；路',
  'we': '我们',
  'weather': '天气',
  'went': '去（go 的过去式）',
  'were': '是（be 的过去式）',
  'what': '什么',
  'whatever': '无论什么',
  'when': '当…时',
  'where': '哪里',
  'whether': '是否',
  'which': '哪一个',
  'while': '当…时；然而',
  'who': '谁',
  'whole': '整个的',
  'why': '为什么',
  'will': '将要',
  'win': '赢',
  'windows': '窗户',
  'with': '和…一起',
  'without': '没有',
  'words': '单词',
  'work': '工作',
  'would': '将会',
  'write': '写',
  'wrong': '错的',

  /* ---- y ---- */
  'year': '年',
  'yesterday': '昨天',
  'yields': '产量；产生',
  'you': '你',
  "you'd": '你会',
  'your': '你的',

  /* ================ 阅读理解那批词 (2026-10 入库, 现并进英语) ================
     这一批是阅读理解题库里的词, 量比原英语题库大(8 篇短文), 单独排在后面,
     按字母分组。要合并进上面那份大表请自便, 键不重复就行。 */

  /* ---- a ---- */
  'abandoned': '被遗弃的；废弃的',
  'able': '能够的',
  'above': '在…上面；超过',
  'academic': '学术的',
  'acceptance': '接受；认可',
  'accepted': '公认的；被接受的',
  'achieve': '实现；达到',
  'achievement': '成就；成绩',
  'achievements': '成就',
  'acquire': '获得；学到',
  'acquired': '后天的；获得的',
  'acting': '表演；演技',
  'action': '行动',
  'activities': '活动',
  'actor': '演员',
  'added': '增加的',
  'addition': '增加 (in addition 此外)',
  'administrators': '管理者；行政人员',
  'admissions': '录取；招生',
  'advantage': '优势；好处',
  'advertise': '做广告',
  'affect': '影响',
  'afraid': '害怕的',
  'age': '年龄；时代',
  'ago': '以前',
  'agree': '同意',
  'agreed': '同意的；达成一致',
  'aim': '目标；旨在',
  'allocation': '分配',
  'allowed': '被允许的',
  'already': '已经',
  'amazing': '令人惊奇的',
  'american': '美国的；美国人',
  'americans': '美国人',
  'among': '在…之中',
  'amsterdam': '阿姆斯特丹（地名）',
  'ancient': '古代的',
  'animal': '动物',
  'animals': '动物',
  'answer': '回答；答案',
  'anxiety': '焦虑；忧虑',
  'apparently': '显然；据说',
  'appear': '出现；显得',
  'appeared': '出现',
  'apply': '应用；申请',
  'appreciation': '欣赏；感激',
  'arduous': '艰巨的；费力的',
  'areas': '区域；领域',
  'argue': '争论；主张',
  'argument': '论点；争论',
  'arm': '手臂',
  'arose': '产生；出现 (arise 的过去式)',
  'arranged': '安排；编曲',
  'arrive': '到达',
  'art': '艺术；美术',
  'article': '文章；物品',
  'artists': '艺术家',
  'ask': '问；要求',
  'asked': '问',
  'asked-for': '所需的；被要求的',
  'asking': '询问',
  'aspect': '方面',
  'aspects': '方面',
  'assumption': '假设；假定',
  'astonishing': '令人惊讶的',
  'athlete': '运动员',
  'athletes': '运动员',
  'attached': '附着的；连接的',
  'attack': '攻击',
  'attacked': '攻击',
  'attempts': '尝试',
  'attending': '出席；照料',
  'attraction': '吸引力；景点',
  'auditorium': '礼堂；观众席',
  'author': '作者',
  'authority': '权威；当局',
  'average': '平均的；一般的',
  'avoiding': '避免',
  'aware': '意识到的；知道的',

  /* ---- b ---- */
  'bad': '坏的',
  'bag': '袋子',
  'ball': '球；舞会',
  'ballet': '芭蕾舞',
  'balls': '球',
  'ban': '禁止',
  'based': '以…为基础',
  'basketball': '篮球',
  'bath': '洗澡；浴缸',
  'battery': '电池',
  'battle': '战斗；斗争',
  'baum': '鲍姆（人名）',
  'beats': '节拍；打败',
  'became': '成为 (become 的过去式)',
  'been': '是 (be 的过去分词)',
  'began': '开始 (begin 的过去式)',
  'beginning': '开始；开端',
  'begins': '开始',
  'being': '存在；生物',
  'beings': '生物',
  'believe': '相信',
  'believed': '相信',
  'beneficial': '有益的',
  'benefit': '好处；受益',
  'best': '最好的',
  'between': '在…之间',
  'biggest': '最大的',
  'billy': '比利（人名）',
  'biology': '生物学',
  'birthplace': '出生地',
  'blackout': '停电；灯火管制',
  'body': '身体；主体',
  'both': '两者都',
  'bought': '买 (buy 的过去式)',
  'bow': '鞠躬；弓',
  'boys': '男孩',
  'brain': '大脑',
  'breathing': '呼吸',
  'bring': '带来',
  'britain': '英国',
  'british': '英国的；英国人',
  'broad': '宽的；广泛的',
  'brother': '兄弟',
  'buildings': '建筑物',
  'built-up': '建成的；组合的',
  'butterflies': '蝴蝶',
  'buyer': '买家',
  'buyers': '买家',
  'by': '由；通过',

  /* ---- c ---- */
  'cabled': '发电报',
  'called': '称为；打电话',
  'came': '来 (come 的过去式)',
  'candlelight': '烛光',
  'car': '汽车；车厢',
  'carried': '携带；运送',
  'cars': '汽车',
  'cases': '情况；案例',
  'cells': '细胞；电池',
  'centuries': '世纪',
  'century': '世纪',
  'certain': '某些；确定的',
  'challenges': '挑战',
  'chances': '机会；可能性',
  'changes': '变化',
  'charge': '收费；指控；充电',
  'cheap': '便宜的',
  'chords': '和弦',
  'claims': '声称；主张',
  'clarity': '清晰；明确',
  'clear': '清楚的；清除',
  'clearly': '清楚地',
  'closely': '紧密地；密切地',
  'coaxed': '劝诱；哄',
  'combined': '结合的；联合的',
  'coming': '即将到来的',
  'community': '社区；群体',
  'compared': '比较 (compared with 与…相比)',
  'competition': '竞争；比赛',
  'complete': '完成；完整的',
  'complex': '复杂的',
  'complexities': '复杂性',
  'complicated': '复杂的',
  'composed': '创作；组成',
  'composer': '作曲家',
  'composers': '作曲家',
  'compositions': '作品；作文',
  'comprise': '包括；由…组成',
  'concern': '关心；涉及',
  'concerned': '有关的；担心的',
  'conclude': '得出结论；结束',
  'conductors': '指挥；导体',
  'conference': '会议',
  'confiscate': '没收；充公',
  'confiscated': '没收；充公',
  'confiscation': '没收；充公',
  'confronts': '面对；对抗',
  'connection': '联系；连接',
  'conrad': '康拉德（人名）',
  'consequently': '因此；结果',
  'consider': '考虑；认为',
  'considerable': '相当大的',
  'contained': '包含',
  'continues': '继续',
  'continuing': '持续的',
  'contraband': '走私货；禁运品',
  'contrast': '对比；对照',
  'control': '控制',
  'controlled': '受控的；被控制的',
  'controlling': '控制',
  'convince': '使信服；说服',
  'coordination': '协调',
  'cornell': '康奈尔（大学名）',
  'corresponds': '对应；相符',
  'costumes': '服装；戏服',
  'council': '委员会；议会',
  'countries': '国家',
  'country': '国家；乡村',
  'countryside': '乡村',
  'course': '课程；过程 (of course 当然)',
  'courses': '课程',
  'cover': '覆盖；涵盖',
  'create': '创造',
  'cup': '杯子；奖杯',
  'current': '当前的；电流',
  'currents': '水流；电流',
  'customs': '海关；习俗',

  /* ---- d ---- */
  'dance': '舞蹈',
  'dancer': '舞蹈演员',
  'dancers': '舞蹈演员',
  'dances': '舞蹈',
  'danger': '危险',
  'dangerous': '危险的',
  'dean': '院长；系主任',
  'declare': '宣布；申报',
  'define': '定义',
  'definition': '定义',
  'deliver': '递送；发表',
  'delivery': '递送；交付',
  'demand': '需求；要求',
  'demands': '需求',
  'depend': '依靠；取决于',
  'dependent': '依赖的',
  'depends': '取决于',
  'depth': '深度',
  'describe': '描述',
  'desired': '想要的；期望的',
  'destroyed': '被毁坏的',
  'detail': '细节',
  'determine': '决定；确定',
  'develop': '发展；开发',
  'developing': '发展中的',
  'dialogue': '对话',
  'did': '做 (do 的过去式)',
  'differed': '不同；相异',
  'difference': '差别',
  'different': '不同的',
  'difficulties': '困难',
  'diploma': '文凭；毕业证书',
  'diplomacy': '外交',
  'disadvantages': '缺点；不利之处',
  'discounts': '折扣',
  'discourage': '使泄气；阻碍',
  'discover': '发现',
  'discovering': '发现',
  'discuss': '讨论',
  'discusses': '讨论',
  'division': '部门；分工',
  'doctor': '医生；博士',
  'does': '做 (do 的第三人称单数)',
  "don't": '不 (do not 的缩写)',
  'down': '向下',
  'dr': '博士 (Dr. 的缩写)',
  'drama': '戏剧',
  'dramas': '戏剧',
  'dramatic': '戏剧性的；巨大的',
  'dramatically': '显著地；戏剧性地',
  'drawing': '绘画；图画',
  'during': '在…期间',
  'dutiable': '应缴税的',
  'duty': '关税；职责',
  'dying': '垂死的；濒临消亡的',

  /* ---- e ---- */
  'early': '早的；早期的',
  'easier': '更容易的',
  'eat': '吃',
  'economy': '经济',
  'educate': '教育',
  'educated': '受过教育的',
  'education': '教育',
  'educational': '教育的',
  'eel': '鳗鱼',
  'eels': '鳗鱼',
  'effect': '效果；影响',
  'effects': '效果；影响',
  'elaborated': '详细阐述的；精心制作的',
  'electric': '电的',
  'electrical': '电的；用电的',
  'electricity': '电；电学',
  'electrocardiogram': '心电图',
  'electroencephalogram': '脑电图',
  'element': '元素；要素',
  'elements': '元素；要素',
  'elevators': '电梯',
  'elsewhere': '在别处',
  'embarrass': '使尴尬',
  'emit': '发出；发射',
  'enactment': '制定；颁布',
  'end': '结束；末端',
  'enjoy': '享受；喜欢',
  'entire': '整个的',
  'entirely': '完全地',
  'environment': '环境',
  'environments': '环境',
  'equal': '相等的；平等的',
  'escalators': '自动扶梯',
  'europe': '欧洲',
  'european': '欧洲的；欧洲人',
  'event': '事件',
  'eventually': '最终',
  'ever': '曾经；无论何时',
  'everyone': '每个人',
  'evolved': '演变的；进化的',
  'exactly': '确切地',
  'examine': '检查；考察',
  'example': '例子 (for example 例如)',
  'except': '除…之外',
  'exchange': '交换；兑换',
  'exchanged': '交换',
  'existed': '存在',
  'existence': '存在',
  'existing': '现有的',
  'expected': '预期的',
  'experimenting': '做实验',
  'expert': '专家',
  'experts': '专家',
  'explained': '解释',
  'extreme': '极端的',

  /* ---- f ---- */
  'face': '面对；脸',
  'fact': '事实 (in fact 事实上)',
  'factor': '因素',
  'factors': '因素',
  'failing': '失败；衰退',
  'failures': '失败',
  'familiar': '熟悉的',
  'fanatical': '狂热的',
  'far': '远的；很',
  'fastest': '最快的',
  'fault': '过错；缺点',
  'feared': '害怕；担心',
  'feats': '功绩；技艺',
  'feels': '感觉',
  'feet': '脚 (foot 的复数)',
  'felt': '感觉 (feel 的过去式)',
  'few': '很少的',
  'fewer': '更少的',
  'field': '领域；田野',
  'fifths': '五分之一；第五',
  'fifty': '五十',
  'fingers': '手指',
  'finished': '完成的',
  'first-class': '头等的；一流的',
  'fixed': '固定的',
  'flat': '平的；公寓',
  'flickering': '闪烁的',
  'following': '下列的；接着的',
  'follows': '跟随；如下',
  'fond': '喜爱的 (be fond of 喜爱)',
  'food': '食物',
  'foolishness': '愚蠢',
  'football': '足球',
  'forces': '力量；部队',
  'forget': '忘记',
  'forgotten': '忘记的',
  'form': '形式；形成',
  'formulated': '系统阐述的；制定的',
  'four': '四',
  'friend': '朋友',
  'fro': '来去 (to and fro 来回地)',
  'full': '满的；完全的',
  'fully': '完全地',
  'function': '功能；运转',
  'furthermore': '此外',
  'future': '未来',

  /* ---- g ---- */
  'game': '游戏；比赛',
  'games': '游戏；比赛',
  'gave': '给 (give 的过去式)',
  'generated': '产生的；生成的',
  'generating': '产生；发电',
  'generator': '发电机',
  'george': '乔治（人名）',
  'give': '给',
  'goals': '目标；进球',
  'goes': '去；进行',
  'going': '去；进行',
  'goods': '商品；货物',
  'gotten': '得到 (get 的过去分词)',
  'gradually': '逐渐地',
  'grasp': '抓住；理解',
  'grateful': '感激的',
  'greater': '更大的',
  'greece': '希腊',
  'greeks': '希腊人',
  'grew': '生长 (grow 的过去式)',
  'grope': '摸索',
  'group': '群体；组',
  'grow': '生长；增长',
  'growing': '增长的',
  'guarantee': '保证',
  'guarantees': '保证',
  'guide': '引导；指南',
  'gymnastic': '体操的',

  /* ---- h ---- */
  'hammers': '锤子；琴槌',
  'hand': '手；方面',
  'hangs': '悬挂',
  'happened': '发生',
  'happening': '发生；事件',
  'hard': '困难的；坚硬的',
  'hardened': '变硬的；使坚强',
  'harder': '更难的；更努力地',
  'hardly': '几乎不',
  'harvard': '哈佛（大学名）',
  'hear': '听见',
  'heart': '心脏；核心',
  'held': '举行；握住 (hold 的过去式)',
  'henry': '亨利（人名）',
  'here': '这里',
  'hesitate': '犹豫',
  'hide': '隐藏',
  'highest': '最高的',
  'highly': '高度地；非常',
  'hired': '雇用的',
  'history': '历史',
  'hit': '打击；命中',
  'hold': '握住；容纳',
  'home-schooling': '在家上学',
  'hopes': '希望',
  'hour': '小时',
  'houses': '房屋',
  'how': '如何',
  'however': '然而',
  'human': '人类的',
  'humanity': '人类；人性',
  'humorous': '幽默的',
  'hundred': '百',
  'hundreds': '数百',
  'hunt': '打猎；搜寻',

  /* ---- i ---- */
  'imagine': '想象',
  'imitations': '模仿；仿制品',
  'immediate': '立即的',
  'impersonated': '模仿；扮演',
  'impersonation': '模仿；扮演',
  'importance': '重要性',
  'important': '重要的',
  'importantly': '重要地 (more importantly 更重要的是)',
  'including': '包括',
  'indians': '印度人；印第安人',
  'independent': '独立的',
  'indifferent': '漠不关心的',
  'individuals': '个人',
  'industrial': '工业的',
  'inferred': '推断出',
  'influence': '影响',
  'inherent': '固有的；内在的',
  'instructions': '指示；说明',
  'instrument': '乐器；仪器',
  'instrumentalists': '器乐演奏者',
  'instruments': '乐器；仪器',
  'intended': '打算；意图',
  'interact': '互动',
  'interest': '兴趣',
  'interested': '感兴趣的',
  'interesting': '有趣的',
  'interrelationships': '相互关系',
  'into': '进入',
  'invented': '发明',
  'involved': '涉及；参与',
  'islands': '岛屿',
  'item': '项目；条目',
  'its': '它的',

  /* ---- j ---- */
  'jolt': '震动；颠簸',
  'journey': '旅程',
  'just': '只是；刚刚',

  /* ---- k ---- */
  'keeping': '保持',
  'kicked': '踢',
  'kind': '种类；友善的',
  'kindergarten': '幼儿园',
  'knowing': '知道',
  'knowledge': '知识',
  'knows': '知道',

  /* ---- l ---- */
  'labor': '劳动；劳动力',
  'lack': '缺乏',
  'land': '土地；着陆',
  'language': '语言',
  'last': '最后的；持续',
  'late': '晚的；迟的',
  'later': '后来',
  'laws': '法律',
  'leaders': '领导者',
  'learn': '学习',
  'learned': '博学的；学会的',
  'length': '长度',
  'less': '更少的',
  'levels': '水平；层次',
  'liable': '有责任的；易于…的',
  'lights': '灯；光',
  'likely': '可能的',
  'limited': '有限的',
  'linked': '连接的；相关的',
  'lipscomb': '利普斯科姆（人名）',
  'list': '列表；名单',
  'little': '小的；很少',
  'lives': '生活；生命',
  'living': '生活；活着的',
  'london': '伦敦（地名）',
  'longer': '更长的',
  'loss': '损失',
  'lost': '失去的；迷路的',
  'luggage': '行李',

  /* ---- m ---- */
  'magic': '魔术；魔法',
  'main': '主要的',
  'mainly': '主要地',
  'makes': '使得；制作',
  'man-made': '人造的',
  'manage': '管理；设法做到',
  'market': '市场',
  'masks': '面具',
  'mason': '梅森（人名）',
  'mass': '大量；群众',
  'material': '材料',
  'materials': '材料',
  'means': '手段；意味着',
  'measures': '措施；测量',
  'medical': '医学的',
  'medicine': '医学；药',
  'meet': '遇见；满足',
  'members': '成员',
  'mention': '提到',
  'mentioned': '提到',
  'mentions': '提到',
  'mere': '仅仅的',
  'methods': '方法',
  'millions': '数百万',
  'mimed': '模拟表演；哑剧表演',
  'missed': '错过；未击中',
  'mistakes': '错误',
  'model': '模型；型号',
  'modern': '现代的',
  'momentarily': '片刻地；暂时地',
  'months': '月份',
  'morning': '早晨',
  'motivate': '激励',
  'movements': '运动；动作',
  'moves': '移动；举措',
  'moving': '移动的；感人的',
  'muscle': '肌肉',
  'muscles': '肌肉',
  'muscular': '肌肉的',
  'music': '音乐',
  'musical': '音乐的',
  'musicians': '音乐家',
  'myriad': '无数的',
  'myself': '我自己',
  'mysteries': '奥秘；谜',
  'myths': '神话；谬见',

  /* ---- n ---- */
  'narrator': '叙述者',
  'national': '国家的',
  'native': '本地的；天生的',
  'natural': '自然的',
  'nature': '自然；本性',
  'needed': '需要的',
  'needs': '需要',
  'nervous': '神经的；紧张的',
  'network': '网络',
  'never': '从不',
  'next': '下一个',
  'night': '夜晚',
  'noise': '噪音',
  'noon': '中午',
  'nor': '也不',
  'note': '笔记；音符',
  'notes': '笔记；音符',
  'noticed': '注意到',
  'numbers': '数字；数量',

  /* ---- o ---- */
  'obligation': '义务；责任',
  'occasionally': '偶尔',
  'officer': '官员；军官',
  'open': '打开；开放的',
  'option': '选择；选项',
  'organization': '组织',
  'organizers': '组织者',
  'origin': '起源',
  'original': '原来的；独创的',
  'origins': '起源',
  'others': '其他人',
  'outdoor': '户外的',
  'outlined': '概述；勾画',
  'overcome': '克服',
  'overlapping': '重叠的',
  'oyster': '牡蛎',

  /* ---- p ---- */
  'package': '包裹；一揽子',
  'paid': '支付 (pay 的过去式)',
  'painter': '画家',
  'painters': '画家',
  'paragraph': '段落',
  'paragraphs': '段落',
  'parents': '父母',
  'park': '公园；停车',
  'parks': '公园',
  'participate': '参与',
  'particular': '特定的 (in particular 尤其)',
  'parts': '部分',
  'passage': '段落；通道',
  'passenger': '乘客',
  'patricia': '帕特里夏（人名）',
  'payment': '支付；报酬',
  'peace': '和平',
  'pence': '便士',
  'percent': '百分之…',
  'percussion': '打击乐',
  'perfectly': '完美地',
  'perform': '表演；执行',
  'performances': '表演',
  'performed': '表演',
  'performer': '表演者',
  'performers': '表演者',
  'performing': '表演',
  'periods': '时期；周期',
  'persisted': '坚持',
  'persuade': '说服',
  'peter': '彼得（人名）',
  'physical': '身体的；物理的',
  'pianists': '钢琴家',
  'piano': '钢琴',
  'picture': '图片；描绘',
  'piece': '一块；作品',
  'places': '地方',
  'plans': '计划',
  'play': '玩；演奏；戏剧',
  'played': '玩；演奏',
  'players': '演奏者；运动员',
  'please': '请；使高兴',
  'plots': '情节',
  'pocket': '口袋',
  'polluted': '被污染的',
  'popular': '流行的',
  'potentially': '潜在地',
  'power': '力量；电力',
  'powerful': '强大的',
  'powers': '能力；权力',
  'prepared': '准备好的',
  'preparing': '准备',
  'presenting': '呈现；表演',
  'preserve': '保存；保护',
  'price': '价格',
  'primarily': '主要地',
  'privileges': '特权',
  'produced': '生产；产生',
  'product': '产品',
  'professional': '专业的',
  'proficiency': '熟练；精通',
  'protected': '受保护的',
  'protection': '保护',
  'provide': '提供',
  'provided': '提供',
  'public': '公共的',
  'public-utility': '公用事业的',
  'pulses': '脉冲；脉搏',
  'punishment': '惩罚',
  'purpose': '目的',

  /* ---- q ---- */
  'quality': '质量；品质',
  'quarter': '四分之一；一刻钟',
  'question': '问题',
  'questions': '问题',
  'quickly': '迅速地',

  /* ---- r ---- */
  'radio': '收音机；无线电',
  'rain': '雨；下雨',
  'randomly': '随机地',
  'ranked': '排名；位居',
  'rationed': '配给的',
  'reach': '到达；够到',
  'reached': '到达',
  'reader': '读者',
  'ready': '准备好的',
  'rearranging': '重新排列；改编',
  'received': '收到',
  'recent': '最近的',
  'recently': '最近',
  'record': '记录；唱片',
  'recorded': '记录的',
  'recreation': '娱乐；消遣',
  'refers': '指的是；提到',
  'refrigerated': '冷藏的',
  'refrigerators': '冰箱',
  'regarded': '被认为 (be regarded as 被视为)',
  'related': '相关的',
  'religious': '宗教的',
  'rely': '依赖 (rely on)',
  'remained': '仍然是；留下',
  'repairs': '修理',
  'repeated': '重复的',
  'replace': '取代',
  'replaced': '取代',
  'replacement': '替代；替换',
  'replied': '回答',
  'reply': '回答',
  'representations': '表现；代表',
  'representative': '代表；典型的',
  'represented': '代表；表现',
  'reptile': '爬行动物',
  'reptiles': '爬行动物',
  'require': '需要；要求',
  'required': '必需的',
  'requirements': '要求',
  'requires': '需要',
  'researcher': '研究人员',
  'reserve': '储备；保留',
  'reserves': '储备',
  'resource': '资源',
  'resources': '资源',
  'responsibilities': '责任',
  'rest': '休息；其余',
  'results': '结果',
  'retained': '保留；保持',
  'return': '返回；回归',
  'revival': '复兴；复活',
  'rhythmical': '有节奏的',
  'riordan': '里奥丹（人名）',
  'rites': '仪式',
  'ritual': '仪式',
  'rituals': '仪式',
  'robert': '罗伯特（人名）',
  'role': '角色；作用',
  'roles': '角色；作用',
  'rolex': '劳力士（手表品牌）',
  'romans': '罗马人',
  'roughly': '大致；粗略地',
  'rowena': '罗伊娜（人名）',
  'rules': '规则；统治',

  /* ---- s ---- */
  'safer': '更安全的',
  'safety': '安全',
  'sarcastic': '讽刺的',
  'says': '说',
  'schedule': '日程；安排',
  'schooling': '学校教育',
  'schools': '学校',
  'science': '科学',
  'scientists': '科学家',
  'scores': '分数；配乐',
  'search': '搜寻',
  'seasonal': '季节性的',
  'seasons': '季节',
  'seats': '座位',
  'secrets': '秘密',
  'sector': '部门；领域',
  'seed': '种子',
  'seemed': '似乎',
  'seems': '似乎',
  'selected': '挑选出的',
  'self-directed': '自主的',
  'selfless': '无私的',
  'seller': '卖方',
  'send': '发送',
  'sends': '发送',
  'sensitive': '敏感的',
  'sentence': '句子',
  'separated': '分开的',
  'serve': '服务；供应',
  'service': '服务',
  'services': '服务',
  'set': '设置；一套',
  'shillings': '先令',
  'shock': '震惊；电击',
  'short': '短的；不足的',
  'shorter': '更短的',
  'show': '展示；表演',
  'shown': '展示 (show 的过去分词)',
  'shrunk': '收缩 (shrink 的过去分词)',
  'silent': '沉默的；无声的',
  'similar': '相似的',
  'singers': '歌手',
  'single': '单一的；单人的',
  'site': '地点；网站',
  'six': '六',
  'skills': '技能',
  'small': '小的',
  'soccer': '足球',
  'social': '社会的；社交的',
  'society': '社会',
  'solemn': '庄严的；肃穆的',
  'sometimes': '有时',
  'sophomore': '大学二年级学生',
  'sought': '寻求 (seek 的过去式)',
  'sound': '声音；听起来',
  'sounds': '声音',
  'spared': '腾出；饶恕',
  'special': '特别的',
  'specialized': '专门的；专业化的',
  'species': '物种',
  'spent': '花费 (spend 的过去式)',
  'spoiled': '被宠坏的；损坏的',
  'spoils': '战利品；破坏',
  'spoke': '说 (speak 的过去式)',
  'sport': '运动',
  'spread': '传播；散布',
  'start': '开始；启动',
  'state': '状态；州；陈述',
  'statements': '陈述；声明',
  'states': '州；状态',
  'stay': '停留',
  'stomachs': '胃',
  'stopped': '停止',
  'storage': '储存',
  'stories': '故事',
  'story': '故事',
  'storytelling': '讲故事',
  'strange': '奇怪的',
  'streets': '街道',
  'strength': '力量',
  'string': '弦；一串',
  'strings': '弦；一串',
  'strong': '强壮的；强烈的',
  'stronger': '更强的',
  'studied': '研究；学习',
  'studies': '研究；学习',
  'study': '学习；研究',
  'studying': '学习',
  'successful': '成功的',
  'suitable': '合适的',
  'sun': '太阳',
  'supernatural': '超自然的',
  'supply': '供应',
  'support': '支持',
  'supporter': '支持者',
  'supporting': '支持',
  'supports': '支持',
  'survive': '幸存；存活',
  'system': '系统',
  'systems': '系统',

  /* ---- t ---- */
  'take': '拿；花费',
  'taking': '拿；花费',
  'tales': '故事；传说',
  'taught': '教 (teach 的过去式)',
  'teaching': '教学',
  'teams': '团队',
  'technique': '技巧；技术',
  'telephones': '电话',
  'televisions': '电视',
  'tennis': '网球',
  'tension': '紧张；张力',
  'terms': '术语；条件',
  'tests': '测试',
  'text': '文本；课文',
  'texture': '质地；纹理',
  'th': '第 (序数词缩写)',
  'theater': '剧院；戏剧',
  'then': '然后；那时',
  'theories': '理论',
  'theory': '理论',
  "they've": '他们已经 (they have 的缩写)',
  'think': '认为；思考',
  'thinks': '认为',
  'thirty': '三十',
  'thoroughly': '彻底地',
  'thousands': '数千',
  'times': '时代；次数',
  'tiny': '微小的',
  'tiredness': '疲倦',
  'title': '标题；头衔',
  'today': '今天',
  'together': '一起',
  'tone': '音调；语气',
  'took': '拿 (take 的过去式)',
  'total': '总数；全部的',
  'totally': '完全地',
  'tougher': '更难的；更艰难的',
  'tourist': '游客',
  'tourists': '游客',
  'towns': '城镇',
  'traces': '痕迹；追溯',
  'traditional': '传统的',
  'traffic': '交通；运输',
  'training': '训练',
  'transaction': '交易',
  'transactions': '交易',
  'transportation': '运输',
  'travels': '旅行',
  'trend': '趋势',
  'true': '真的',
  'tune': '调音；曲调',
  'tuners': '调音师；调谐器',
  'turning': '转动；变成',
  'twelve': '十二',
  'twenty': '二十',
  'twice': '两次',
  'two': '二',
  'types': '类型',

  /* ---- u ---- */
  'ugly': '丑陋的',
  'ultimately': '最终',
  'understand': '理解',
  'understanding': '理解',
  'undisturbed': '不受干扰的',
  'unexpected': '意外的',
  'unfortunate': '不幸的',
  'united': '联合的 (the United States 美国)',
  'universities': '大学',
  'university': '大学',
  'unknown': '未知的',
  'unlike': '不像；与…不同',
  'unnaturally': '不自然地',
  'unpredictable': '不可预测的',
  'unusual': '不寻常的',
  'upon': '在…之上',
  'used': '用过的；过去常常',
  'useful': '有用的',
  'uses': '使用',
  'using': '使用',
  'usual': '通常的',
  'usually': '通常',
  'utilities': '公用事业',
  'utterly': '完全地',

  /* ---- v ---- */
  'valid': '有效的',
  'value': '价值',
  'variety': '多样性；种类',
  'various': '各种各样的',
  'veiled': '隐蔽的；蒙面的',
  'view': '观点；景色',
  'viewed': '看待；观看',
  'visited': '参观',
  'vocal': '声乐的；发声的',
  'voltage': '电压',
  'volts': '伏特',

  /* ---- w ---- */
  'waiting': '等待',
  'wall': '墙',
  'wanted': '想要',
  'warn': '警告',
  'warranties': '保修；担保',
  'watch': '观看；手表',
  'water': '水',
  'waves': '波；浪潮',
  'ways': '方式',
  "we'll": '我们将 (we will 的缩写)',
  'weaknesses': '弱点',
  'wearing': '穿着；磨损',
  'week': '周',
  'well': '好；井',
  'whereas': '然而；尽管',
  'whichever': '无论哪个',
  'widely': '广泛地',
  'wildlife': '野生动物',
  'working': '工作；运转',
  'works': '作品；工作',
  'world': '世界',
  'wrangler': '牧马人；辩论队员',
  'writer': '作家',
  'writes': '写',
  'written': '书面的 (write 的过去分词)',
  'wrote': '写 (write 的过去式)',

  /* ---- y ---- */
  'years': '年',
  'yes': '是',
  'yet': '还；然而',
  'young': '年轻的',
  'younger': '更年轻的',

  /* ================ 单句翻译那批词 (2026-10 入库) ================
     单句翻译题库 (20 个英文句子) 里的词, 按字母分组, 单独排在后面。
     键和上面两份不重复。 */

  /* ---- a ---- */
  'accurate': '准确的；精确的',
  'advertisement': '广告',
  'advertisements': '广告',
  'agreement': '协议；同意',
  'agriculture': '农业',
  'appropriate': '恰当的；合适的',

  /* ---- b ---- */
  'bankrupt': '破产的 (go bankrupt 破产)',
  'big': '大的 (big data 大数据)',

  /* ---- c ---- */
  'calls': '通话；电话 (call 的复数)',
  'cancel': '取消',
  'cigarettes': '香烟',
  'communication': '通信；交流',
  'companies': '公司 (company 的复数)',
  'complaint': '投诉；抱怨',
  'completed': '完成的 (complete 的过去分词)',
  'confidence': '信心；信任',
  'conversations': '通话；交谈',
  'cost': '成本；花费',
  'costs': '成本 (cost 的复数)',
  'covered': '包含；被覆盖 (cover 的过去分词)',
  'crimes': '犯罪；罪行',
  'culture': '文化',
  'customer': '客户；顾客',

  /* ---- d ---- */
  'damaged': '受损的；损坏的 (damage 的过去分词)',
  'dealers': '经销商',
  'decides': '决定 (decide 的第三人称单数)',
  'definitely': '肯定地；的确',
  'devices': '设备；装置',
  'doubt': '怀疑 (no doubt 毫无疑问)',
  'due': '由于 (due to 由于)',

  /* ---- e ---- */
  'economic': '经济的',
  'employer': '雇主',
  'enroll': '报名；注册',
  'established': '建立 (establish 的过去分词)',
  'expenses': '费用；开支',

  /* ---- f ---- */
  'families': '家庭 (family 的复数)',
  'features': '特点；特征',
  'finally': '最终；最后',
  'friends': '朋友 (friend 的复数)',
  'friendship': '友谊',

  /* ---- g ---- */
  'gps': 'GPS；全球定位系统',
  'granted': '理所当然 (take ... for granted)',
  'growth': '增长',

  /* ---- h ---- */
  'higher': '更高的 (high 的比较级)',

  /* ---- i ---- */
  'incomes': '收入',
  'increase': '增加；提高',
  'increased': '增加的 (increase 的过去分词)',
  'industry': '工业；行业',
  'investigation': '调查',

  /* ---- k ---- */
  'key': '关键；钥匙',

  /* ---- l ---- */
  'limit': '限制',
  'lower': '更低的 (low 的比较级)',

  /* ---- m ---- */
  'making': '使得；制作 (make 的现在分词)',
  'manufacturing': '制造 (manufacturing process 制造过程)',
  'maps': '地图',
  'marketing': '营销 (marketing strategies 营销策略)',
  'meeting': '会议',
  'men': '男人 (man 的复数)',
  'mobile': '移动的 (mobile phone 手机)',

  /* ---- n ---- */
  'notice': '通知；注意 (written notice 书面通知)',

  /* ---- o ---- */
  'obviously': '显然',
  'occur': '发生',
  'ones': '那些 (one 的复数)',
  'online': '在线的；网上',
  'owning': '拥有 (own 的现在分词)',

  /* ---- p ---- */
  'party': '一方；聚会 (Party A 甲方)',
  'pay': '支付；付款',
  'personal': '私人的；个人的',
  'phone': '电话；手机',
  'poor': '糟糕的；贫穷的',
  'president': '总裁；总统 (vice president 副总裁)',
  'process': '过程；流程',
  'production': '生产 (cost of production 生产成本)',
  'programme': '项目；计划 (英式拼法)',
  'promptly': '及时地；迅速地',
  'purchase': '购买',

  /* ---- r ---- */
  'refused': '拒绝 (refuse 的过去式)',
  'regaining': '重获 (regain 的现在分词)',
  'repair': '修理',
  'reports': '报告',
  'respond': '回复；回应',
  'returning': '退还；返回 (return 的现在分词)',

  /* ---- s ---- */
  'save': '节省；保存',
  'scanned': '扫描 (scan 的过去分词)',
  'selling': '销售 (selling price 售价)',
  'showing': '表明；展示 (show 的现在分词)',
  'smaller': '更小的 (small 的比较级)',
  'smoke': '吸烟；烟',
  'solved': '解决 (solve 的过去分词)',
  'strategies': '策略',
  'striking': '引人注目的；显著的',
  'sure': '确保 (make sure 确保)',

  /* ---- t ---- */
  'terrible': '糟糕的；可怕的',
  'transit': '运输 (in transit 在运输中)',

  /* ---- u ---- */
  'urgent': '紧急的',

  /* ---- v ---- */
  'vice': '副的 (vice president 副总裁)',

  /* ---- w ---- */
  'well-educated': '受过良好教育的',
  'western': '西方的',
  'wholesale': '批发的 (wholesale price 批发价)',

  /* ---- y ---- */
  "you're": '你是 (you are 的缩写)',

  /* ---- 数据结构题库 ----
     除了一般的英文词, 里面还有几个 C 语言记号 —— 它们不是"词", 是解析器把
     `head->next` / `n-1` / `O(nlog₂n)` 按字母切开后的碎片 (见 app.js 的 WORD_RE),
     键得照切出来的样子写, 否则悬停查不到。 */
  'binary': '二分的；二叉的 (binary tree 二叉树)',
  'connected': '连通的 (connected graph 连通图)',
  'datastructure': '数据结构 (data structure 连写在一起)',
  'double': '双的；两倍的 (double linked list 双向链表)',
  'graph': '图 (顶点和边组成的结构)',
  'head': '头指针 (指向链表第一个结点)',
  'head-': '就是 head, 头指针 (C 语言里写成 head->next)',
  'link': '链；链接 (指针 pointer 又叫链 link)',
  'log': '对数 (log₂n 是以 2 为底 n 的对数)',
  'n-': 'n 减 1 里的 "n-" (n-1 表示比 n 少一个)',
  'n-i': 'n 减 i (顺序表插入时要后移 n-i+1 个元素)',
  'nlog': 'n 乘 log n (常见的时间复杂度量级)',
  'nlogn': 'n 乘 log n (常见的时间复杂度量级)',
  'node': '结点',
  'null': '空 (C 语言里 NULL 表示空指针)',
  'pointer': '指针 (存放地址的变量)',
  'prior': '前趋 (prior 指向直接前驱结点)',
  'software': '软件',
  'str': '字符串 (string 的缩写)',
  'tree': '树',

  /* ---- 操作系统题库 ---- */
  'bios': '基本输入输出系统 (Basic Input/Output System)',
  'compaction': '拼接；紧凑 (把分散的空闲区集中到一块)',
  'cpu': '中央处理器 (Central Processing Unit)',
  'dma': '直接存储器存取 (Direct Memory Access, 不经过 CPU 直接在内存和外设间传送数据)',
  'fcb': '文件控制块 (File Control Block)',
  'fifo': '先进先出 (First In First Out, 先来的先被淘汰)',
  'lfu': '最不经常使用 (Least Frequently Used, 淘汰访问次数最少的页面)',
  'linux': 'Linux 操作系统',
  'lru': '最近最少使用 (Least Recently Used, 淘汰最久没被访问的页面)',
  'opt': '最优置换算法 (Optimal, 淘汰以后最久不会用到的页面, 只存在于理论中)',
  'scan': '扫描算法 (磁盘调度里的电梯算法, 磁头来回扫)',
  'unix': 'UNIX 操作系统',
  // 解答题/综合计算题里冒出来的记号: 不算单词, 但悬停时总得说一句, 免得当成生词去背
  'ah': '十六进制地址里的两位 (2F6AH 的后两位), 不是单词',
  'bf': '十六进制地址 BF6AH 的前两位, 不是单词',
  'fat': '文件分配表 (File Allocation Table)',
  'kb': 'KB (Kilobyte, 千字节, 1KB = 1024 字节)',
  'ms': '毫秒 (millisecond, 1 秒 = 1000 毫秒)',
  'pcb': '进程控制块 (Process Control Block, 存着进程的全部描述信息)',
  'pn': 'Pn —— 第 n 个写进程 (题目给进程起的名字), 不是单词',
  'pr': 'Pr —— 读进程 (题目给进程起的名字), 不是单词',

};
